# Site settings
title: Tijs Verkoyen
email: site@verkoyen.eu
author: Tijs Verkoyen
description: This is a site from/about Tijs Verkoyen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://verkoyen.eu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
